/**
 * Patreon Tools Registry
 * Registers Patreon Makeover Mode tools with SWEObeyMe
 */

export function getPatreonToolDefinitions() {
  const patreonTools = [
    {
      name: 'patreon_fetch_content',
      priority: 70,
      description: 'Fetch current Patreon content including tiers, posts, about page, and campaign info. This is the ONLY way to retrieve Patreon content for analysis. MUST use this tool before attempting to analyze or rewrite Patreon content.',
      inputSchema: {
        type: 'object',
        properties: {
          content_type: {
            type: 'string',
            enum: ['tiers', 'posts', 'about', 'campaign', 'all'],
            description: 'Type of content to fetch from Patreon',
          },
        },
        required: ['content_type'],
      },
    },
    {
      name: 'patreon_generate_rewrite_plan',
      priority: 70,
      description: 'Analyze current Patreon content and generate a structured rewrite plan with recommendations for improvement. This tool analyzes weaknesses, inconsistencies, and opportunities in your Patreon content. MUST use this tool after fetching content with patreon_fetch_content.',
      inputSchema: {
        type: 'object',
        properties: {
          current_content: {
            type: 'object',
            description: 'Current Patreon content fetched via patreon_fetch_content',
          },
          focus_areas: {
            type: 'array',
            items: { type: 'string' },
            description: 'Areas to focus on for rewrite (e.g., ["tiers", "about", "welcome"])',
          },
        },
        required: ['current_content'],
      },
    },
    {
      name: 'patreon_write_drafts',
      priority: 70,
      description: 'Generate new Patreon content drafts into local markdown files based on the approved rewrite plan. This tool creates about.md, tiers.md, and welcome.md files in the specified output directory. MUST use this tool after approving a rewrite plan generated by patreon_generate_rewrite_plan.',
      inputSchema: {
        type: 'object',
        properties: {
          plan: {
            type: 'object',
            description: 'Rewrite plan generated by patreon_generate_rewrite_plan',
          },
          output_dir: {
            type: 'string',
            description: 'Directory to write draft files (default: patreon-drafts)',
          },
        },
        required: ['plan'],
      },
    },
    {
      name: 'patreon_apply_changes',
      priority: 60,
      description: 'Apply generated drafts to live Patreon content via API. This tool requires explicit confirmation (confirm=true) and is optional - you can manually paste the drafts into Patreon instead. WARNING: This operation modifies live Patreon content. MUST set confirm=true to proceed.',
      inputSchema: {
        type: 'object',
        properties: {
          drafts: {
            type: 'array',
            items: { type: 'object' },
            description: 'Array of draft files to apply to Patreon',
          },
          confirm: {
            type: 'boolean',
            description: 'Explicit confirmation to apply changes (required, must be true)',
          },
        },
        required: ['drafts', 'confirm'],
      },
    },
  ];

  return patreonTools.sort((a, b) => (b.priority || 0) - (a.priority || 0));
}
